name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy gh-pages

    env:
      GHPAGE_SECRET: ${{secrets.PUBLISH_GH_PAGE_SECRET}}
      COMMIT_USERNAME: ghactions[bot]
      COMMIT_EMAIL: ghactions[bot]@users.noreply.github.com

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git config --global user.name $COMMIT_USERNAME
        git config --global user.email $COMMIT_EMAIL
        git remote set-url origin https://GHPAGE_SECRET@github.com/$GITHUB_REPOSITORY.git
        npm run gh-pages
